version: '3.7'
services:
  mysql:
    image: mysql:8
    ports:
      - '3306:3306/tcp'
    environment:
      MYSQL_ROOT_PASSWORD: yes
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass

  ## Для использования раскомментировать Postgres и закомментировать MySQL
#  postgresql:
#    image: postgres
#    ports:
#      - '5432:5432/tcp'
#    environment:
#      POSTGRES_PASSWORD: pass
#      POSTGRES_USER: app
#      POSTGRES_DB: app

  node:
    image: "node"
    ports:
      - '9999:9999/tcp'
    working_dir: /home/node/app
    volumes:
      - ./gate-simulator/:/home/node/app
    command: "npm start"
