version: '3.7'
services:
  mysql:
    image: mysql:8
    ports:
      - '3306:3306/tcp'
    volumes:
      - ./dataMySQL:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: yes
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
