version: '3.7'
services:
  postgresql:
    image: postgres
    ports:
      - '5432:5432/tcp'
    volumes:
      - ./dataPostgreSQL:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: app
      POSTGRES_DB: app